services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    volumes:
      - processed_data_vol:/app/processed_data
    env_file:
      - .env

volumes:
  processed_data_vol: 